env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
builds:
- id: "bytepad"
  main: ./cmd/bytepad/main.go
  binary: bytepad
  goos:
    - darwin
    - linux
    - windows
- id: "cap2rom"
  main: ./cmd/cap2rom/main.go
  binary: cap2rom
  goos:
    - darwin
    - linux
    - windows
archives:
- replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    386: 32bit
    amd64: 64bit
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
